name: tfc-apply-run

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '.github/workflows/tfc-*.yml'

permissions:
  contents: read

concurrency:
  group: tfc-apply-${{ github.ref }}
  cancel-in-progress: true

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
  CONFIG_DIRECTORY: ${{ vars.TF_CONFIG_DIRECTORY || '.' }}

jobs:
  terraform-cloud-apply-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate workflow inputs
        run: |
          missing=0
          for var in TF_CLOUD_ORGANIZATION TF_WORKSPACE TF_API_TOKEN CONFIG_DIRECTORY; do
            if [ -z "${!var}" ]; then
              echo "::error::${var} is not configured."
              missing=1
            fi
          done
          if [ $missing -eq 1 ]; then
            echo "Required Terraform Cloud settings are missing. Configure repository variables/secrets before rerunning."
            exit 1
          fi

      - name: Upload configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create apply run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          message: "Apply run triggered from GitHub Actions CI ${{ github.sha }}"

      - name: Apply Terraform Cloud run
        if: ${{ fromJSON(steps.create-run.outputs.payload).data.attributes.actions.IsConfirmable }}
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        id: apply
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "GitHub Actions approved apply for ${{ github.sha }}"

      - name: Output run information
        run: |
          echo "Terraform Cloud run URL: ${{ steps.create-run.outputs.run_link }}"
          echo "Run status: ${{ steps.create-run.outputs.run_status }}"
